### ISSUE TITLE
No Module Named instaloader

### ISSUE THREAD

**Issue by networktoast** [Meta-bhsc/RAVAGE#2]
When I tried running RAVAGE i got the ModuleNotFound Error for instaloader

**Comment by Quancivillious-Hornswoggle** [comment]
Yeah thats when the packages are not in root, if you just run sudo pip install -r requirements.txt it should install it as root and you should be able to run RAVAGE as root.

**Comment by Quancivillious-Hornswoggle** [comment]
I updated the readme so if you just follow the directions there you should be able to get it working.
